sudo: required
services:
  - docker

before_install:
  - docker build -t sean0923/docker-react-step-grid -f Dockerfile.dev .

scripts:
  - docker run sean0923/docker-react-step-grid npm run test -- --coverage
 