sudo: required
services:
  - docker

before_install:
  - docker build -t sean0923/docker-react-step-grid -f Dockerfile.dev .

script:
  - docker run sean0923/docker-react-step-grid npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-235941291634"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
 